package cn.beijing.ssfh.entity;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_name
     *
     * @mbggenerated
     */
    private String addressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_code
     *
     * @mbggenerated
     */
    private String addressCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_type
     *
     * @mbggenerated
     */
    private String addressType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_level
     *
     * @mbggenerated
     */
    private String addressLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_id
     *
     * @return the value of address.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_id
     *
     * @param addressId the value for address.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_name
     *
     * @return the value of address.address_name
     *
     * @mbggenerated
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_name
     *
     * @param addressName the value for address.address_name
     *
     * @mbggenerated
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_code
     *
     * @return the value of address.address_code
     *
     * @mbggenerated
     */
    public String getAddressCode() {
        return addressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_code
     *
     * @param addressCode the value for address.address_code
     *
     * @mbggenerated
     */
    public void setAddressCode(String addressCode) {
        this.addressCode = addressCode == null ? null : addressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_type
     *
     * @return the value of address.address_type
     *
     * @mbggenerated
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_type
     *
     * @param addressType the value for address.address_type
     *
     * @mbggenerated
     */
    public void setAddressType(String addressType) {
        this.addressType = addressType == null ? null : addressType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_level
     *
     * @return the value of address.address_level
     *
     * @mbggenerated
     */
    public String getAddressLevel() {
        return addressLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_level
     *
     * @param addressLevel the value for address.address_level
     *
     * @mbggenerated
     */
    public void setAddressLevel(String addressLevel) {
        this.addressLevel = addressLevel == null ? null : addressLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.parent_id
     *
     * @return the value of address.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.parent_id
     *
     * @param parentId the value for address.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}