package cn.beijing.ssfh.entity;

public class Chapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.chapter_id
     *
     * @mbggenerated
     */
    private Integer chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.study_parts_id
     *
     * @mbggenerated
     */
    private Integer studyPartsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.chapter_name
     *
     * @mbggenerated
     */
    private String chapterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.chapter_duration
     *
     * @mbggenerated
     */
    private Integer chapterDuration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.chapter_id
     *
     * @return the value of chapter.chapter_id
     *
     * @mbggenerated
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.chapter_id
     *
     * @param chapterId the value for chapter.chapter_id
     *
     * @mbggenerated
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.study_parts_id
     *
     * @return the value of chapter.study_parts_id
     *
     * @mbggenerated
     */
    public Integer getStudyPartsId() {
        return studyPartsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.study_parts_id
     *
     * @param studyPartsId the value for chapter.study_parts_id
     *
     * @mbggenerated
     */
    public void setStudyPartsId(Integer studyPartsId) {
        this.studyPartsId = studyPartsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.chapter_name
     *
     * @return the value of chapter.chapter_name
     *
     * @mbggenerated
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.chapter_name
     *
     * @param chapterName the value for chapter.chapter_name
     *
     * @mbggenerated
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.chapter_duration
     *
     * @return the value of chapter.chapter_duration
     *
     * @mbggenerated
     */
    public Integer getChapterDuration() {
        return chapterDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.chapter_duration
     *
     * @param chapterDuration the value for chapter.chapter_duration
     *
     * @mbggenerated
     */
    public void setChapterDuration(Integer chapterDuration) {
        this.chapterDuration = chapterDuration;
    }
}