package cn.beijing.ssfh.entity;

public class CourseTables {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_tables.course_tables_id
     *
     * @mbggenerated
     */
    private Integer courseTablesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_tables.day_time_id
     *
     * @mbggenerated
     */
    private Integer dayTimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_tables.classroom_id
     *
     * @mbggenerated
     */
    private Integer classroomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_tables.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_tables.date_time_id
     *
     * @mbggenerated
     */
    private Integer dateTimeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_tables.course_tables_id
     *
     * @return the value of course_tables.course_tables_id
     *
     * @mbggenerated
     */
    public Integer getCourseTablesId() {
        return courseTablesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_tables.course_tables_id
     *
     * @param courseTablesId the value for course_tables.course_tables_id
     *
     * @mbggenerated
     */
    public void setCourseTablesId(Integer courseTablesId) {
        this.courseTablesId = courseTablesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_tables.day_time_id
     *
     * @return the value of course_tables.day_time_id
     *
     * @mbggenerated
     */
    public Integer getDayTimeId() {
        return dayTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_tables.day_time_id
     *
     * @param dayTimeId the value for course_tables.day_time_id
     *
     * @mbggenerated
     */
    public void setDayTimeId(Integer dayTimeId) {
        this.dayTimeId = dayTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_tables.classroom_id
     *
     * @return the value of course_tables.classroom_id
     *
     * @mbggenerated
     */
    public Integer getClassroomId() {
        return classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_tables.classroom_id
     *
     * @param classroomId the value for course_tables.classroom_id
     *
     * @mbggenerated
     */
    public void setClassroomId(Integer classroomId) {
        this.classroomId = classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_tables.grade_id
     *
     * @return the value of course_tables.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_tables.grade_id
     *
     * @param gradeId the value for course_tables.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_tables.date_time_id
     *
     * @return the value of course_tables.date_time_id
     *
     * @mbggenerated
     */
    public Integer getDateTimeId() {
        return dateTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_tables.date_time_id
     *
     * @param dateTimeId the value for course_tables.date_time_id
     *
     * @mbggenerated
     */
    public void setDateTimeId(Integer dateTimeId) {
        this.dateTimeId = dateTimeId;
    }
}