package cn.beijing.ssfh.entity;

public class CoursePlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.course_plan_id
     *
     * @mbggenerated
     */
    private Integer coursePlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.chapter_id
     *
     * @mbggenerated
     */
    private Integer chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.schedule
     *
     * @mbggenerated
     */
    private Integer schedule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.course_plan_id
     *
     * @return the value of course_plan.course_plan_id
     *
     * @mbggenerated
     */
    public Integer getCoursePlanId() {
        return coursePlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.course_plan_id
     *
     * @param coursePlanId the value for course_plan.course_plan_id
     *
     * @mbggenerated
     */
    public void setCoursePlanId(Integer coursePlanId) {
        this.coursePlanId = coursePlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.grade_id
     *
     * @return the value of course_plan.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.grade_id
     *
     * @param gradeId the value for course_plan.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.chapter_id
     *
     * @return the value of course_plan.chapter_id
     *
     * @mbggenerated
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.chapter_id
     *
     * @param chapterId the value for course_plan.chapter_id
     *
     * @mbggenerated
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.schedule
     *
     * @return the value of course_plan.schedule
     *
     * @mbggenerated
     */
    public Integer getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.schedule
     *
     * @param schedule the value for course_plan.schedule
     *
     * @mbggenerated
     */
    public void setSchedule(Integer schedule) {
        this.schedule = schedule;
    }
}