package cn.beijing.ssfh.entity;

public class DepartmentalRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_role.departmental_role_id
     *
     * @mbggenerated
     */
    private Integer departmentalRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_role.department_id
     *
     * @mbggenerated
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_role.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_role.departmental_role_id
     *
     * @return the value of departmental_role.departmental_role_id
     *
     * @mbggenerated
     */
    public Integer getDepartmentalRoleId() {
        return departmentalRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_role.departmental_role_id
     *
     * @param departmentalRoleId the value for departmental_role.departmental_role_id
     *
     * @mbggenerated
     */
    public void setDepartmentalRoleId(Integer departmentalRoleId) {
        this.departmentalRoleId = departmentalRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_role.department_id
     *
     * @return the value of departmental_role.department_id
     *
     * @mbggenerated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_role.department_id
     *
     * @param departmentId the value for departmental_role.department_id
     *
     * @mbggenerated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_role.role_id
     *
     * @return the value of departmental_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_role.role_id
     *
     * @param roleId the value for departmental_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}