package cn.beijing.ssfh.entity;

import java.util.Date;

public class EnterpriseRecruitmentInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.enterprise_recruitment_information_id
     *
     * @mbggenerated
     */
    private Integer enterpriseRecruitmentInformationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.recruiting_post
     *
     * @mbggenerated
     */
    private String recruitingPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.recruitment_salary
     *
     * @mbggenerated
     */
    private String recruitmentSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.hiring
     *
     * @mbggenerated
     */
    private Integer hiring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.educational_requirements
     *
     * @mbggenerated
     */
    private String educationalRequirements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.foreign_language_requirements
     *
     * @mbggenerated
     */
    private String foreignLanguageRequirements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.mode_of_recruitment
     *
     * @mbggenerated
     */
    private String modeOfRecruitment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.work_address
     *
     * @mbggenerated
     */
    private String workAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_recruitment_information.date_of_recruitment
     *
     * @mbggenerated
     */
    private Date dateOfRecruitment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.enterprise_recruitment_information_id
     *
     * @return the value of enterprise_recruitment_information.enterprise_recruitment_information_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseRecruitmentInformationId() {
        return enterpriseRecruitmentInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.enterprise_recruitment_information_id
     *
     * @param enterpriseRecruitmentInformationId the value for enterprise_recruitment_information.enterprise_recruitment_information_id
     *
     * @mbggenerated
     */
    public void setEnterpriseRecruitmentInformationId(Integer enterpriseRecruitmentInformationId) {
        this.enterpriseRecruitmentInformationId = enterpriseRecruitmentInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.enterprise_id
     *
     * @return the value of enterprise_recruitment_information.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.enterprise_id
     *
     * @param enterpriseId the value for enterprise_recruitment_information.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.recruiting_post
     *
     * @return the value of enterprise_recruitment_information.recruiting_post
     *
     * @mbggenerated
     */
    public String getRecruitingPost() {
        return recruitingPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.recruiting_post
     *
     * @param recruitingPost the value for enterprise_recruitment_information.recruiting_post
     *
     * @mbggenerated
     */
    public void setRecruitingPost(String recruitingPost) {
        this.recruitingPost = recruitingPost == null ? null : recruitingPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.recruitment_salary
     *
     * @return the value of enterprise_recruitment_information.recruitment_salary
     *
     * @mbggenerated
     */
    public String getRecruitmentSalary() {
        return recruitmentSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.recruitment_salary
     *
     * @param recruitmentSalary the value for enterprise_recruitment_information.recruitment_salary
     *
     * @mbggenerated
     */
    public void setRecruitmentSalary(String recruitmentSalary) {
        this.recruitmentSalary = recruitmentSalary == null ? null : recruitmentSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.hiring
     *
     * @return the value of enterprise_recruitment_information.hiring
     *
     * @mbggenerated
     */
    public Integer getHiring() {
        return hiring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.hiring
     *
     * @param hiring the value for enterprise_recruitment_information.hiring
     *
     * @mbggenerated
     */
    public void setHiring(Integer hiring) {
        this.hiring = hiring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.educational_requirements
     *
     * @return the value of enterprise_recruitment_information.educational_requirements
     *
     * @mbggenerated
     */
    public String getEducationalRequirements() {
        return educationalRequirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.educational_requirements
     *
     * @param educationalRequirements the value for enterprise_recruitment_information.educational_requirements
     *
     * @mbggenerated
     */
    public void setEducationalRequirements(String educationalRequirements) {
        this.educationalRequirements = educationalRequirements == null ? null : educationalRequirements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.foreign_language_requirements
     *
     * @return the value of enterprise_recruitment_information.foreign_language_requirements
     *
     * @mbggenerated
     */
    public String getForeignLanguageRequirements() {
        return foreignLanguageRequirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.foreign_language_requirements
     *
     * @param foreignLanguageRequirements the value for enterprise_recruitment_information.foreign_language_requirements
     *
     * @mbggenerated
     */
    public void setForeignLanguageRequirements(String foreignLanguageRequirements) {
        this.foreignLanguageRequirements = foreignLanguageRequirements == null ? null : foreignLanguageRequirements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.mode_of_recruitment
     *
     * @return the value of enterprise_recruitment_information.mode_of_recruitment
     *
     * @mbggenerated
     */
    public String getModeOfRecruitment() {
        return modeOfRecruitment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.mode_of_recruitment
     *
     * @param modeOfRecruitment the value for enterprise_recruitment_information.mode_of_recruitment
     *
     * @mbggenerated
     */
    public void setModeOfRecruitment(String modeOfRecruitment) {
        this.modeOfRecruitment = modeOfRecruitment == null ? null : modeOfRecruitment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.work_address
     *
     * @return the value of enterprise_recruitment_information.work_address
     *
     * @mbggenerated
     */
    public String getWorkAddress() {
        return workAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.work_address
     *
     * @param workAddress the value for enterprise_recruitment_information.work_address
     *
     * @mbggenerated
     */
    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress == null ? null : workAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_recruitment_information.date_of_recruitment
     *
     * @return the value of enterprise_recruitment_information.date_of_recruitment
     *
     * @mbggenerated
     */
    public Date getDateOfRecruitment() {
        return dateOfRecruitment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_recruitment_information.date_of_recruitment
     *
     * @param dateOfRecruitment the value for enterprise_recruitment_information.date_of_recruitment
     *
     * @mbggenerated
     */
    public void setDateOfRecruitment(Date dateOfRecruitment) {
        this.dateOfRecruitment = dateOfRecruitment;
    }
}