package cn.beijing.ssfh.entity;

public class EnterpriseContact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_contact.enterprise_contact_id
     *
     * @mbggenerated
     */
    private Integer enterpriseContactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_contact.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_contact.contact_name
     *
     * @mbggenerated
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_contact.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_contact.fixed_telephone
     *
     * @mbggenerated
     */
    private String fixedTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_contact.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_contact.contact_position
     *
     * @mbggenerated
     */
    private String contactPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_contact.number_of_days_not_connected
     *
     * @mbggenerated
     */
    private Integer numberOfDaysNotConnected;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_contact.enterprise_contact_id
     *
     * @return the value of enterprise_contact.enterprise_contact_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseContactId() {
        return enterpriseContactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_contact.enterprise_contact_id
     *
     * @param enterpriseContactId the value for enterprise_contact.enterprise_contact_id
     *
     * @mbggenerated
     */
    public void setEnterpriseContactId(Integer enterpriseContactId) {
        this.enterpriseContactId = enterpriseContactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_contact.enterprise_id
     *
     * @return the value of enterprise_contact.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_contact.enterprise_id
     *
     * @param enterpriseId the value for enterprise_contact.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_contact.contact_name
     *
     * @return the value of enterprise_contact.contact_name
     *
     * @mbggenerated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_contact.contact_name
     *
     * @param contactName the value for enterprise_contact.contact_name
     *
     * @mbggenerated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_contact.phone
     *
     * @return the value of enterprise_contact.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_contact.phone
     *
     * @param phone the value for enterprise_contact.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_contact.fixed_telephone
     *
     * @return the value of enterprise_contact.fixed_telephone
     *
     * @mbggenerated
     */
    public String getFixedTelephone() {
        return fixedTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_contact.fixed_telephone
     *
     * @param fixedTelephone the value for enterprise_contact.fixed_telephone
     *
     * @mbggenerated
     */
    public void setFixedTelephone(String fixedTelephone) {
        this.fixedTelephone = fixedTelephone == null ? null : fixedTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_contact.email
     *
     * @return the value of enterprise_contact.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_contact.email
     *
     * @param email the value for enterprise_contact.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_contact.contact_position
     *
     * @return the value of enterprise_contact.contact_position
     *
     * @mbggenerated
     */
    public String getContactPosition() {
        return contactPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_contact.contact_position
     *
     * @param contactPosition the value for enterprise_contact.contact_position
     *
     * @mbggenerated
     */
    public void setContactPosition(String contactPosition) {
        this.contactPosition = contactPosition == null ? null : contactPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_contact.number_of_days_not_connected
     *
     * @return the value of enterprise_contact.number_of_days_not_connected
     *
     * @mbggenerated
     */
    public Integer getNumberOfDaysNotConnected() {
        return numberOfDaysNotConnected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_contact.number_of_days_not_connected
     *
     * @param numberOfDaysNotConnected the value for enterprise_contact.number_of_days_not_connected
     *
     * @mbggenerated
     */
    public void setNumberOfDaysNotConnected(Integer numberOfDaysNotConnected) {
        this.numberOfDaysNotConnected = numberOfDaysNotConnected;
    }
}