package cn.beijing.ssfh.entity;

public class Enterprise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_name
     *
     * @mbggenerated
     */
    private String enterpriseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_scale
     *
     * @mbggenerated
     */
    private String enterpriseScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_nature
     *
     * @mbggenerated
     */
    private String enterpriseNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_industry
     *
     * @mbggenerated
     */
    private String enterpriseIndustry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_id
     *
     * @return the value of enterprise.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_id
     *
     * @param enterpriseId the value for enterprise.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.address_id
     *
     * @return the value of enterprise.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.address_id
     *
     * @param addressId the value for enterprise.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_name
     *
     * @return the value of enterprise.enterprise_name
     *
     * @mbggenerated
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_name
     *
     * @param enterpriseName the value for enterprise.enterprise_name
     *
     * @mbggenerated
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_scale
     *
     * @return the value of enterprise.enterprise_scale
     *
     * @mbggenerated
     */
    public String getEnterpriseScale() {
        return enterpriseScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_scale
     *
     * @param enterpriseScale the value for enterprise.enterprise_scale
     *
     * @mbggenerated
     */
    public void setEnterpriseScale(String enterpriseScale) {
        this.enterpriseScale = enterpriseScale == null ? null : enterpriseScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_nature
     *
     * @return the value of enterprise.enterprise_nature
     *
     * @mbggenerated
     */
    public String getEnterpriseNature() {
        return enterpriseNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_nature
     *
     * @param enterpriseNature the value for enterprise.enterprise_nature
     *
     * @mbggenerated
     */
    public void setEnterpriseNature(String enterpriseNature) {
        this.enterpriseNature = enterpriseNature == null ? null : enterpriseNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_industry
     *
     * @return the value of enterprise.enterprise_industry
     *
     * @mbggenerated
     */
    public String getEnterpriseIndustry() {
        return enterpriseIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_industry
     *
     * @param enterpriseIndustry the value for enterprise.enterprise_industry
     *
     * @mbggenerated
     */
    public void setEnterpriseIndustry(String enterpriseIndustry) {
        this.enterpriseIndustry = enterpriseIndustry == null ? null : enterpriseIndustry.trim();
    }
}