package cn.beijing.ssfh.entity;

public class EnterpriseTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_teacher.enterprise_teacher_id
     *
     * @mbggenerated
     */
    private Integer enterpriseTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_teacher.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_teacher.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_teacher.enterprise_teacher_id
     *
     * @return the value of enterprise_teacher.enterprise_teacher_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseTeacherId() {
        return enterpriseTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_teacher.enterprise_teacher_id
     *
     * @param enterpriseTeacherId the value for enterprise_teacher.enterprise_teacher_id
     *
     * @mbggenerated
     */
    public void setEnterpriseTeacherId(Integer enterpriseTeacherId) {
        this.enterpriseTeacherId = enterpriseTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_teacher.teacher_id
     *
     * @return the value of enterprise_teacher.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_teacher.teacher_id
     *
     * @param teacherId the value for enterprise_teacher.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_teacher.enterprise_id
     *
     * @return the value of enterprise_teacher.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_teacher.enterprise_id
     *
     * @param enterpriseId the value for enterprise_teacher.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }
}