package cn.beijing.ssfh.entity;

import java.util.Date;

public class EnterpriseMaintenanceInformationSheet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_maintenance_information_sheet.enterprise_maintenance_information_sheet_id
     *
     * @mbggenerated
     */
    private Integer enterpriseMaintenanceInformationSheetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_maintenance_information_sheet.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_maintenance_information_sheet.time_of_return_visit
     *
     * @mbggenerated
     */
    private Date timeOfReturnVisit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_maintenance_information_sheet.return_to_the_person
     *
     * @mbggenerated
     */
    private String returnToThePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_maintenance_information_sheet.return_to_the_content
     *
     * @mbggenerated
     */
    private String returnToTheContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_maintenance_information_sheet.enterprise_maintenance_information_sheet_id
     *
     * @return the value of enterprise_maintenance_information_sheet.enterprise_maintenance_information_sheet_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseMaintenanceInformationSheetId() {
        return enterpriseMaintenanceInformationSheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_maintenance_information_sheet.enterprise_maintenance_information_sheet_id
     *
     * @param enterpriseMaintenanceInformationSheetId the value for enterprise_maintenance_information_sheet.enterprise_maintenance_information_sheet_id
     *
     * @mbggenerated
     */
    public void setEnterpriseMaintenanceInformationSheetId(Integer enterpriseMaintenanceInformationSheetId) {
        this.enterpriseMaintenanceInformationSheetId = enterpriseMaintenanceInformationSheetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_maintenance_information_sheet.enterprise_id
     *
     * @return the value of enterprise_maintenance_information_sheet.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_maintenance_information_sheet.enterprise_id
     *
     * @param enterpriseId the value for enterprise_maintenance_information_sheet.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_maintenance_information_sheet.time_of_return_visit
     *
     * @return the value of enterprise_maintenance_information_sheet.time_of_return_visit
     *
     * @mbggenerated
     */
    public Date getTimeOfReturnVisit() {
        return timeOfReturnVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_maintenance_information_sheet.time_of_return_visit
     *
     * @param timeOfReturnVisit the value for enterprise_maintenance_information_sheet.time_of_return_visit
     *
     * @mbggenerated
     */
    public void setTimeOfReturnVisit(Date timeOfReturnVisit) {
        this.timeOfReturnVisit = timeOfReturnVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_maintenance_information_sheet.return_to_the_person
     *
     * @return the value of enterprise_maintenance_information_sheet.return_to_the_person
     *
     * @mbggenerated
     */
    public String getReturnToThePerson() {
        return returnToThePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_maintenance_information_sheet.return_to_the_person
     *
     * @param returnToThePerson the value for enterprise_maintenance_information_sheet.return_to_the_person
     *
     * @mbggenerated
     */
    public void setReturnToThePerson(String returnToThePerson) {
        this.returnToThePerson = returnToThePerson == null ? null : returnToThePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_maintenance_information_sheet.return_to_the_content
     *
     * @return the value of enterprise_maintenance_information_sheet.return_to_the_content
     *
     * @mbggenerated
     */
    public String getReturnToTheContent() {
        return returnToTheContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_maintenance_information_sheet.return_to_the_content
     *
     * @param returnToTheContent the value for enterprise_maintenance_information_sheet.return_to_the_content
     *
     * @mbggenerated
     */
    public void setReturnToTheContent(String returnToTheContent) {
        this.returnToTheContent = returnToTheContent == null ? null : returnToTheContent.trim();
    }
}