package cn.beijing.ssfh.entity;

import java.util.Date;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.state_id
     *
     * @mbggenerated
     */
    private Integer stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_num
     *
     * @mbggenerated
     */
    private String gradeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_name
     *
     * @mbggenerated
     */
    private String gradeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_size
     *
     * @mbggenerated
     */
    private Integer gradeSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_course
     *
     * @mbggenerated
     */
    private String gradeCourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_id
     *
     * @return the value of grade.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_id
     *
     * @param gradeId the value for grade.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.state_id
     *
     * @return the value of grade.state_id
     *
     * @mbggenerated
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.state_id
     *
     * @param stateId the value for grade.state_id
     *
     * @mbggenerated
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_num
     *
     * @return the value of grade.grade_num
     *
     * @mbggenerated
     */
    public String getGradeNum() {
        return gradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_num
     *
     * @param gradeNum the value for grade.grade_num
     *
     * @mbggenerated
     */
    public void setGradeNum(String gradeNum) {
        this.gradeNum = gradeNum == null ? null : gradeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_name
     *
     * @return the value of grade.grade_name
     *
     * @mbggenerated
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_name
     *
     * @param gradeName the value for grade.grade_name
     *
     * @mbggenerated
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName == null ? null : gradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_size
     *
     * @return the value of grade.grade_size
     *
     * @mbggenerated
     */
    public Integer getGradeSize() {
        return gradeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_size
     *
     * @param gradeSize the value for grade.grade_size
     *
     * @mbggenerated
     */
    public void setGradeSize(Integer gradeSize) {
        this.gradeSize = gradeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_course
     *
     * @return the value of grade.grade_course
     *
     * @mbggenerated
     */
    public String getGradeCourse() {
        return gradeCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_course
     *
     * @param gradeCourse the value for grade.grade_course
     *
     * @mbggenerated
     */
    public void setGradeCourse(String gradeCourse) {
        this.gradeCourse = gradeCourse == null ? null : gradeCourse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.start_time
     *
     * @return the value of grade.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.start_time
     *
     * @param startTime the value for grade.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}