package cn.beijing.ssfh.entity;

public class GradeSircle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_sircle.grade_sircle_id
     *
     * @mbggenerated
     */
    private Integer gradeSircleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_sircle.week_id
     *
     * @mbggenerated
     */
    private Integer weekId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_sircle.sircle_time_part_id
     *
     * @mbggenerated
     */
    private Integer sircleTimePartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_sircle.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_sircle.grade_sircle_id
     *
     * @return the value of grade_sircle.grade_sircle_id
     *
     * @mbggenerated
     */
    public Integer getGradeSircleId() {
        return gradeSircleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_sircle.grade_sircle_id
     *
     * @param gradeSircleId the value for grade_sircle.grade_sircle_id
     *
     * @mbggenerated
     */
    public void setGradeSircleId(Integer gradeSircleId) {
        this.gradeSircleId = gradeSircleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_sircle.week_id
     *
     * @return the value of grade_sircle.week_id
     *
     * @mbggenerated
     */
    public Integer getWeekId() {
        return weekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_sircle.week_id
     *
     * @param weekId the value for grade_sircle.week_id
     *
     * @mbggenerated
     */
    public void setWeekId(Integer weekId) {
        this.weekId = weekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_sircle.sircle_time_part_id
     *
     * @return the value of grade_sircle.sircle_time_part_id
     *
     * @mbggenerated
     */
    public Integer getSircleTimePartId() {
        return sircleTimePartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_sircle.sircle_time_part_id
     *
     * @param sircleTimePartId the value for grade_sircle.sircle_time_part_id
     *
     * @mbggenerated
     */
    public void setSircleTimePartId(Integer sircleTimePartId) {
        this.sircleTimePartId = sircleTimePartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_sircle.grade_id
     *
     * @return the value of grade_sircle.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_sircle.grade_id
     *
     * @param gradeId the value for grade_sircle.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
}