package cn.beijing.ssfh.entity;

import java.util.Date;

public class GraduationStudentVisitRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_student_visit_record.graduation_student_visit_record_id
     *
     * @mbggenerated
     */
    private Integer graduationStudentVisitRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_student_visit_record.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_student_visit_record.review_content
     *
     * @mbggenerated
     */
    private String reviewContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduation_student_visit_record.visit_time
     *
     * @mbggenerated
     */
    private Date visitTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_student_visit_record.graduation_student_visit_record_id
     *
     * @return the value of graduation_student_visit_record.graduation_student_visit_record_id
     *
     * @mbggenerated
     */
    public Integer getGraduationStudentVisitRecordId() {
        return graduationStudentVisitRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_student_visit_record.graduation_student_visit_record_id
     *
     * @param graduationStudentVisitRecordId the value for graduation_student_visit_record.graduation_student_visit_record_id
     *
     * @mbggenerated
     */
    public void setGraduationStudentVisitRecordId(Integer graduationStudentVisitRecordId) {
        this.graduationStudentVisitRecordId = graduationStudentVisitRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_student_visit_record.student_id
     *
     * @return the value of graduation_student_visit_record.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_student_visit_record.student_id
     *
     * @param studentId the value for graduation_student_visit_record.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_student_visit_record.review_content
     *
     * @return the value of graduation_student_visit_record.review_content
     *
     * @mbggenerated
     */
    public String getReviewContent() {
        return reviewContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_student_visit_record.review_content
     *
     * @param reviewContent the value for graduation_student_visit_record.review_content
     *
     * @mbggenerated
     */
    public void setReviewContent(String reviewContent) {
        this.reviewContent = reviewContent == null ? null : reviewContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduation_student_visit_record.visit_time
     *
     * @return the value of graduation_student_visit_record.visit_time
     *
     * @mbggenerated
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduation_student_visit_record.visit_time
     *
     * @param visitTime the value for graduation_student_visit_record.visit_time
     *
     * @mbggenerated
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }
}