package cn.beijing.ssfh.entity;

public class GradeTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_teacher.grade_teacher_id
     *
     * @mbggenerated
     */
    private Integer gradeTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_teacher.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_teacher.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_teacher.grade_teacher_id
     *
     * @return the value of grade_teacher.grade_teacher_id
     *
     * @mbggenerated
     */
    public Integer getGradeTeacherId() {
        return gradeTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_teacher.grade_teacher_id
     *
     * @param gradeTeacherId the value for grade_teacher.grade_teacher_id
     *
     * @mbggenerated
     */
    public void setGradeTeacherId(Integer gradeTeacherId) {
        this.gradeTeacherId = gradeTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_teacher.grade_id
     *
     * @return the value of grade_teacher.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_teacher.grade_id
     *
     * @param gradeId the value for grade_teacher.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_teacher.teacher_id
     *
     * @return the value of grade_teacher.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_teacher.teacher_id
     *
     * @param teacherId the value for grade_teacher.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}