package cn.beijing.ssfh.entity;

public class GradeStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_student.grade_student_id
     *
     * @mbggenerated
     */
    private Integer gradeStudentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_student.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_student.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_student.grade_student_id
     *
     * @return the value of grade_student.grade_student_id
     *
     * @mbggenerated
     */
    public Integer getGradeStudentId() {
        return gradeStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_student.grade_student_id
     *
     * @param gradeStudentId the value for grade_student.grade_student_id
     *
     * @mbggenerated
     */
    public void setGradeStudentId(Integer gradeStudentId) {
        this.gradeStudentId = gradeStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_student.student_id
     *
     * @return the value of grade_student.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_student.student_id
     *
     * @param studentId the value for grade_student.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_student.grade_id
     *
     * @return the value of grade_student.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_student.grade_id
     *
     * @param gradeId the value for grade_student.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
}