package cn.beijing.ssfh.entity;

public class MenuPermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_permissions.menu_permissions_id
     *
     * @mbggenerated
     */
    private Integer menuPermissionsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_permissions.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_permissions.permissions_id
     *
     * @mbggenerated
     */
    private Integer permissionsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_permissions.menu_permissions_id
     *
     * @return the value of menu_permissions.menu_permissions_id
     *
     * @mbggenerated
     */
    public Integer getMenuPermissionsId() {
        return menuPermissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_permissions.menu_permissions_id
     *
     * @param menuPermissionsId the value for menu_permissions.menu_permissions_id
     *
     * @mbggenerated
     */
    public void setMenuPermissionsId(Integer menuPermissionsId) {
        this.menuPermissionsId = menuPermissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_permissions.menu_id
     *
     * @return the value of menu_permissions.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_permissions.menu_id
     *
     * @param menuId the value for menu_permissions.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_permissions.permissions_id
     *
     * @return the value of menu_permissions.permissions_id
     *
     * @mbggenerated
     */
    public Integer getPermissionsId() {
        return permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_permissions.permissions_id
     *
     * @param permissionsId the value for menu_permissions.permissions_id
     *
     * @mbggenerated
     */
    public void setPermissionsId(Integer permissionsId) {
        this.permissionsId = permissionsId;
    }
}