package cn.beijing.ssfh.entity;

public class Permissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.permissions_id
     *
     * @mbggenerated
     */
    private Integer permissionsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.permissions_name
     *
     * @mbggenerated
     */
    private String permissionsName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.permissions_id
     *
     * @return the value of permissions.permissions_id
     *
     * @mbggenerated
     */
    public Integer getPermissionsId() {
        return permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.permissions_id
     *
     * @param permissionsId the value for permissions.permissions_id
     *
     * @mbggenerated
     */
    public void setPermissionsId(Integer permissionsId) {
        this.permissionsId = permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.permissions_name
     *
     * @return the value of permissions.permissions_name
     *
     * @mbggenerated
     */
    public String getPermissionsName() {
        return permissionsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.permissions_name
     *
     * @param permissionsName the value for permissions.permissions_name
     *
     * @mbggenerated
     */
    public void setPermissionsName(String permissionsName) {
        this.permissionsName = permissionsName == null ? null : permissionsName.trim();
    }
}