package cn.beijing.ssfh.entity;

import java.util.Date;

public class Production {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.production_id
     *
     * @mbggenerated
     */
    private Integer productionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.major_id
     *
     * @mbggenerated
     */
    private Integer majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.version_num
     *
     * @mbggenerated
     */
    private Double versionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.version_state
     *
     * @mbggenerated
     */
    private Integer versionState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.production_id
     *
     * @return the value of production.production_id
     *
     * @mbggenerated
     */
    public Integer getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.production_id
     *
     * @param productionId the value for production.production_id
     *
     * @mbggenerated
     */
    public void setProductionId(Integer productionId) {
        this.productionId = productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.major_id
     *
     * @return the value of production.major_id
     *
     * @mbggenerated
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.major_id
     *
     * @param majorId the value for production.major_id
     *
     * @mbggenerated
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.version_num
     *
     * @return the value of production.version_num
     *
     * @mbggenerated
     */
    public Double getVersionNum() {
        return versionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.version_num
     *
     * @param versionNum the value for production.version_num
     *
     * @mbggenerated
     */
    public void setVersionNum(Double versionNum) {
        this.versionNum = versionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.start_time
     *
     * @return the value of production.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.start_time
     *
     * @param startTime the value for production.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.end_time
     *
     * @return the value of production.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.end_time
     *
     * @param endTime the value for production.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.version_state
     *
     * @return the value of production.version_state
     *
     * @mbggenerated
     */
    public Integer getVersionState() {
        return versionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.version_state
     *
     * @param versionState the value for production.version_state
     *
     * @mbggenerated
     */
    public void setVersionState(Integer versionState) {
        this.versionState = versionState;
    }
}