package cn.beijing.ssfh.entity;

public class RolePermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.role_permissions_id
     *
     * @mbggenerated
     */
    private Integer rolePermissionsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.permissions_id
     *
     * @mbggenerated
     */
    private Integer permissionsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.role_permissions_id
     *
     * @return the value of role_permissions.role_permissions_id
     *
     * @mbggenerated
     */
    public Integer getRolePermissionsId() {
        return rolePermissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.role_permissions_id
     *
     * @param rolePermissionsId the value for role_permissions.role_permissions_id
     *
     * @mbggenerated
     */
    public void setRolePermissionsId(Integer rolePermissionsId) {
        this.rolePermissionsId = rolePermissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.permissions_id
     *
     * @return the value of role_permissions.permissions_id
     *
     * @mbggenerated
     */
    public Integer getPermissionsId() {
        return permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.permissions_id
     *
     * @param permissionsId the value for role_permissions.permissions_id
     *
     * @mbggenerated
     */
    public void setPermissionsId(Integer permissionsId) {
        this.permissionsId = permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.role_id
     *
     * @return the value of role_permissions.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.role_id
     *
     * @param roleId the value for role_permissions.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}