package cn.beijing.ssfh.entity;

public class SircleTimePart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sircle_time_part.sircle_time_part_id
     *
     * @mbggenerated
     */
    private Integer sircleTimePartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sircle_time_part.time_part
     *
     * @mbggenerated
     */
    private Integer timePart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sircle_time_part.sircle_time_part_id
     *
     * @return the value of sircle_time_part.sircle_time_part_id
     *
     * @mbggenerated
     */
    public Integer getSircleTimePartId() {
        return sircleTimePartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sircle_time_part.sircle_time_part_id
     *
     * @param sircleTimePartId the value for sircle_time_part.sircle_time_part_id
     *
     * @mbggenerated
     */
    public void setSircleTimePartId(Integer sircleTimePartId) {
        this.sircleTimePartId = sircleTimePartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sircle_time_part.time_part
     *
     * @return the value of sircle_time_part.time_part
     *
     * @mbggenerated
     */
    public Integer getTimePart() {
        return timePart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sircle_time_part.time_part
     *
     * @param timePart the value for sircle_time_part.time_part
     *
     * @mbggenerated
     */
    public void setTimePart(Integer timePart) {
        this.timePart = timePart;
    }
}