package cn.beijing.ssfh.entity;

public class State {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.state_id
     *
     * @mbggenerated
     */
    private Integer stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.state_type
     *
     * @mbggenerated
     */
    private Integer stateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.state_name
     *
     * @mbggenerated
     */
    private String stateName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.state_id
     *
     * @return the value of state.state_id
     *
     * @mbggenerated
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.state_id
     *
     * @param stateId the value for state.state_id
     *
     * @mbggenerated
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.state_type
     *
     * @return the value of state.state_type
     *
     * @mbggenerated
     */
    public Integer getStateType() {
        return stateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.state_type
     *
     * @param stateType the value for state.state_type
     *
     * @mbggenerated
     */
    public void setStateType(Integer stateType) {
        this.stateType = stateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.state_name
     *
     * @return the value of state.state_name
     *
     * @mbggenerated
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.state_name
     *
     * @param stateName the value for state.state_name
     *
     * @mbggenerated
     */
    public void setStateName(String stateName) {
        this.stateName = stateName == null ? null : stateName.trim();
    }
}