package cn.beijing.ssfh.entity;

import java.util.Date;

public class StudentInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.student_name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.student_num
     *
     * @mbggenerated
     */
    private String studentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.native_place
     *
     * @mbggenerated
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.home_address
     *
     * @mbggenerated
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.document_type
     *
     * @mbggenerated
     */
    private Integer documentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.document_number
     *
     * @mbggenerated
     */
    private String documentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.birth_date
     *
     * @mbggenerated
     */
    private Date birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.professiona
     *
     * @mbggenerated
     */
    private String professiona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.graduation_date
     *
     * @mbggenerated
     */
    private Date graduationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.parents_name
     *
     * @mbggenerated
     */
    private String parentsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.parents_tel
     *
     * @mbggenerated
     */
    private String parentsTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.emergency_contact
     *
     * @mbggenerated
     */
    private String emergencyContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.emergency_contact_tel
     *
     * @mbggenerated
     */
    private String emergencyContactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.household_registration_code
     *
     * @mbggenerated
     */
    private String householdRegistrationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_information.home_address_code
     *
     * @mbggenerated
     */
    private String homeAddressCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.student_id
     *
     * @return the value of student_information.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.student_id
     *
     * @param studentId the value for student_information.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.address_id
     *
     * @return the value of student_information.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.address_id
     *
     * @param addressId the value for student_information.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.student_name
     *
     * @return the value of student_information.student_name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.student_name
     *
     * @param studentName the value for student_information.student_name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.student_num
     *
     * @return the value of student_information.student_num
     *
     * @mbggenerated
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.student_num
     *
     * @param studentNum the value for student_information.student_num
     *
     * @mbggenerated
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.gender
     *
     * @return the value of student_information.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.gender
     *
     * @param gender the value for student_information.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.native_place
     *
     * @return the value of student_information.native_place
     *
     * @mbggenerated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.native_place
     *
     * @param nativePlace the value for student_information.native_place
     *
     * @mbggenerated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.home_address
     *
     * @return the value of student_information.home_address
     *
     * @mbggenerated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.home_address
     *
     * @param homeAddress the value for student_information.home_address
     *
     * @mbggenerated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.telephone
     *
     * @return the value of student_information.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.telephone
     *
     * @param telephone the value for student_information.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.email
     *
     * @return the value of student_information.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.email
     *
     * @param email the value for student_information.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.document_type
     *
     * @return the value of student_information.document_type
     *
     * @mbggenerated
     */
    public Integer getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.document_type
     *
     * @param documentType the value for student_information.document_type
     *
     * @mbggenerated
     */
    public void setDocumentType(Integer documentType) {
        this.documentType = documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.document_number
     *
     * @return the value of student_information.document_number
     *
     * @mbggenerated
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.document_number
     *
     * @param documentNumber the value for student_information.document_number
     *
     * @mbggenerated
     */
    public void setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber == null ? null : documentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.nation
     *
     * @return the value of student_information.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.nation
     *
     * @param nation the value for student_information.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.birth_date
     *
     * @return the value of student_information.birth_date
     *
     * @mbggenerated
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.birth_date
     *
     * @param birthDate the value for student_information.birth_date
     *
     * @mbggenerated
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.age
     *
     * @return the value of student_information.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.age
     *
     * @param age the value for student_information.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.education
     *
     * @return the value of student_information.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.education
     *
     * @param education the value for student_information.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.professiona
     *
     * @return the value of student_information.professiona
     *
     * @mbggenerated
     */
    public String getProfessiona() {
        return professiona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.professiona
     *
     * @param professiona the value for student_information.professiona
     *
     * @mbggenerated
     */
    public void setProfessiona(String professiona) {
        this.professiona = professiona == null ? null : professiona.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.graduation_date
     *
     * @return the value of student_information.graduation_date
     *
     * @mbggenerated
     */
    public Date getGraduationDate() {
        return graduationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.graduation_date
     *
     * @param graduationDate the value for student_information.graduation_date
     *
     * @mbggenerated
     */
    public void setGraduationDate(Date graduationDate) {
        this.graduationDate = graduationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.parents_name
     *
     * @return the value of student_information.parents_name
     *
     * @mbggenerated
     */
    public String getParentsName() {
        return parentsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.parents_name
     *
     * @param parentsName the value for student_information.parents_name
     *
     * @mbggenerated
     */
    public void setParentsName(String parentsName) {
        this.parentsName = parentsName == null ? null : parentsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.parents_tel
     *
     * @return the value of student_information.parents_tel
     *
     * @mbggenerated
     */
    public String getParentsTel() {
        return parentsTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.parents_tel
     *
     * @param parentsTel the value for student_information.parents_tel
     *
     * @mbggenerated
     */
    public void setParentsTel(String parentsTel) {
        this.parentsTel = parentsTel == null ? null : parentsTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.emergency_contact
     *
     * @return the value of student_information.emergency_contact
     *
     * @mbggenerated
     */
    public String getEmergencyContact() {
        return emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.emergency_contact
     *
     * @param emergencyContact the value for student_information.emergency_contact
     *
     * @mbggenerated
     */
    public void setEmergencyContact(String emergencyContact) {
        this.emergencyContact = emergencyContact == null ? null : emergencyContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.emergency_contact_tel
     *
     * @return the value of student_information.emergency_contact_tel
     *
     * @mbggenerated
     */
    public String getEmergencyContactTel() {
        return emergencyContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.emergency_contact_tel
     *
     * @param emergencyContactTel the value for student_information.emergency_contact_tel
     *
     * @mbggenerated
     */
    public void setEmergencyContactTel(String emergencyContactTel) {
        this.emergencyContactTel = emergencyContactTel == null ? null : emergencyContactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.household_registration_code
     *
     * @return the value of student_information.household_registration_code
     *
     * @mbggenerated
     */
    public String getHouseholdRegistrationCode() {
        return householdRegistrationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.household_registration_code
     *
     * @param householdRegistrationCode the value for student_information.household_registration_code
     *
     * @mbggenerated
     */
    public void setHouseholdRegistrationCode(String householdRegistrationCode) {
        this.householdRegistrationCode = householdRegistrationCode == null ? null : householdRegistrationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_information.home_address_code
     *
     * @return the value of student_information.home_address_code
     *
     * @mbggenerated
     */
    public String getHomeAddressCode() {
        return homeAddressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_information.home_address_code
     *
     * @param homeAddressCode the value for student_information.home_address_code
     *
     * @mbggenerated
     */
    public void setHomeAddressCode(String homeAddressCode) {
        this.homeAddressCode = homeAddressCode == null ? null : homeAddressCode.trim();
    }
}