package cn.beijing.ssfh.entity;

public class Tbuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.tbuser_id
     *
     * @mbggenerated
     */
    private Integer tbuserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.user_info_id
     *
     * @mbggenerated
     */
    private Integer userInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.tbuser_id
     *
     * @return the value of tbuser.tbuser_id
     *
     * @mbggenerated
     */
    public Integer getTbuserId() {
        return tbuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.tbuser_id
     *
     * @param tbuserId the value for tbuser.tbuser_id
     *
     * @mbggenerated
     */
    public void setTbuserId(Integer tbuserId) {
        this.tbuserId = tbuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.user_info_id
     *
     * @return the value of tbuser.user_info_id
     *
     * @mbggenerated
     */
    public Integer getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.user_info_id
     *
     * @param userInfoId the value for tbuser.user_info_id
     *
     * @mbggenerated
     */
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.username
     *
     * @return the value of tbuser.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.username
     *
     * @param username the value for tbuser.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.password
     *
     * @return the value of tbuser.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.password
     *
     * @param password the value for tbuser.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}