package cn.beijing.ssfh.entity;

import java.util.Date;

public class TestPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.test_paper_id
     *
     * @mbggenerated
     */
    private Integer testPaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.path_id
     *
     * @mbggenerated
     */
    private Integer pathId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.test_paper_url
     *
     * @mbggenerated
     */
    private String testPaperUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.test_paper_name
     *
     * @mbggenerated
     */
    private String testPaperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_paper.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.test_paper_id
     *
     * @return the value of test_paper.test_paper_id
     *
     * @mbggenerated
     */
    public Integer getTestPaperId() {
        return testPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.test_paper_id
     *
     * @param testPaperId the value for test_paper.test_paper_id
     *
     * @mbggenerated
     */
    public void setTestPaperId(Integer testPaperId) {
        this.testPaperId = testPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.path_id
     *
     * @return the value of test_paper.path_id
     *
     * @mbggenerated
     */
    public Integer getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.path_id
     *
     * @param pathId the value for test_paper.path_id
     *
     * @mbggenerated
     */
    public void setPathId(Integer pathId) {
        this.pathId = pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.teacher_id
     *
     * @return the value of test_paper.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.teacher_id
     *
     * @param teacherId the value for test_paper.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.test_paper_url
     *
     * @return the value of test_paper.test_paper_url
     *
     * @mbggenerated
     */
    public String getTestPaperUrl() {
        return testPaperUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.test_paper_url
     *
     * @param testPaperUrl the value for test_paper.test_paper_url
     *
     * @mbggenerated
     */
    public void setTestPaperUrl(String testPaperUrl) {
        this.testPaperUrl = testPaperUrl == null ? null : testPaperUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.test_paper_name
     *
     * @return the value of test_paper.test_paper_name
     *
     * @mbggenerated
     */
    public String getTestPaperName() {
        return testPaperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.test_paper_name
     *
     * @param testPaperName the value for test_paper.test_paper_name
     *
     * @mbggenerated
     */
    public void setTestPaperName(String testPaperName) {
        this.testPaperName = testPaperName == null ? null : testPaperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.create_time
     *
     * @return the value of test_paper.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.create_time
     *
     * @param createTime the value for test_paper.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_paper.details
     *
     * @return the value of test_paper.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_paper.details
     *
     * @param details the value for test_paper.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}