package cn.beijing.ssfh.entity;

public class UploadPath {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_path.path_id
     *
     * @mbggenerated
     */
    private Integer pathId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_path.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_path.path_name
     *
     * @mbggenerated
     */
    private String pathName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_path.path_id
     *
     * @return the value of upload_path.path_id
     *
     * @mbggenerated
     */
    public Integer getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_path.path_id
     *
     * @param pathId the value for upload_path.path_id
     *
     * @mbggenerated
     */
    public void setPathId(Integer pathId) {
        this.pathId = pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_path.path
     *
     * @return the value of upload_path.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_path.path
     *
     * @param path the value for upload_path.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_path.path_name
     *
     * @return the value of upload_path.path_name
     *
     * @mbggenerated
     */
    public String getPathName() {
        return pathName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_path.path_name
     *
     * @param pathName the value for upload_path.path_name
     *
     * @mbggenerated
     */
    public void setPathName(String pathName) {
        this.pathName = pathName == null ? null : pathName.trim();
    }
}