package cn.beijing.ssfh.entity;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_info_id
     *
     * @mbggenerated
     */
    private Integer userInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.employee_num
     *
     * @mbggenerated
     */
    private String employeeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.native_place
     *
     * @mbggenerated
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.home_address
     *
     * @mbggenerated
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.document_type
     *
     * @mbggenerated
     */
    private Integer documentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.document_number
     *
     * @mbggenerated
     */
    private String documentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birth_date
     *
     * @mbggenerated
     */
    private Date birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.professiona
     *
     * @mbggenerated
     */
    private String professiona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.emergency_contact
     *
     * @mbggenerated
     */
    private String emergencyContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.emergency_contact_phone
     *
     * @mbggenerated
     */
    private String emergencyContactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.home_address_code
     *
     * @mbggenerated
     */
    private String homeAddressCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.household_registration_code
     *
     * @mbggenerated
     */
    private String householdRegistrationCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_info_id
     *
     * @return the value of user_info.user_info_id
     *
     * @mbggenerated
     */
    public Integer getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_info_id
     *
     * @param userInfoId the value for user_info.user_info_id
     *
     * @mbggenerated
     */
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address_id
     *
     * @return the value of user_info.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address_id
     *
     * @param addressId the value for user_info.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.employee_num
     *
     * @return the value of user_info.employee_num
     *
     * @mbggenerated
     */
    public String getEmployeeNum() {
        return employeeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.employee_num
     *
     * @param employeeNum the value for user_info.employee_num
     *
     * @mbggenerated
     */
    public void setEmployeeNum(String employeeNum) {
        this.employeeNum = employeeNum == null ? null : employeeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.native_place
     *
     * @return the value of user_info.native_place
     *
     * @mbggenerated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.native_place
     *
     * @param nativePlace the value for user_info.native_place
     *
     * @mbggenerated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.home_address
     *
     * @return the value of user_info.home_address
     *
     * @mbggenerated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.home_address
     *
     * @param homeAddress the value for user_info.home_address
     *
     * @mbggenerated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.telephone
     *
     * @return the value of user_info.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.telephone
     *
     * @param telephone the value for user_info.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.document_type
     *
     * @return the value of user_info.document_type
     *
     * @mbggenerated
     */
    public Integer getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.document_type
     *
     * @param documentType the value for user_info.document_type
     *
     * @mbggenerated
     */
    public void setDocumentType(Integer documentType) {
        this.documentType = documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.document_number
     *
     * @return the value of user_info.document_number
     *
     * @mbggenerated
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.document_number
     *
     * @param documentNumber the value for user_info.document_number
     *
     * @mbggenerated
     */
    public void setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber == null ? null : documentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nation
     *
     * @return the value of user_info.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nation
     *
     * @param nation the value for user_info.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birth_date
     *
     * @return the value of user_info.birth_date
     *
     * @mbggenerated
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birth_date
     *
     * @param birthDate the value for user_info.birth_date
     *
     * @mbggenerated
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age
     *
     * @return the value of user_info.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age
     *
     * @param age the value for user_info.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.education
     *
     * @return the value of user_info.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.education
     *
     * @param education the value for user_info.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.professiona
     *
     * @return the value of user_info.professiona
     *
     * @mbggenerated
     */
    public String getProfessiona() {
        return professiona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.professiona
     *
     * @param professiona the value for user_info.professiona
     *
     * @mbggenerated
     */
    public void setProfessiona(String professiona) {
        this.professiona = professiona == null ? null : professiona.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.emergency_contact
     *
     * @return the value of user_info.emergency_contact
     *
     * @mbggenerated
     */
    public String getEmergencyContact() {
        return emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.emergency_contact
     *
     * @param emergencyContact the value for user_info.emergency_contact
     *
     * @mbggenerated
     */
    public void setEmergencyContact(String emergencyContact) {
        this.emergencyContact = emergencyContact == null ? null : emergencyContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.emergency_contact_phone
     *
     * @return the value of user_info.emergency_contact_phone
     *
     * @mbggenerated
     */
    public String getEmergencyContactPhone() {
        return emergencyContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.emergency_contact_phone
     *
     * @param emergencyContactPhone the value for user_info.emergency_contact_phone
     *
     * @mbggenerated
     */
    public void setEmergencyContactPhone(String emergencyContactPhone) {
        this.emergencyContactPhone = emergencyContactPhone == null ? null : emergencyContactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.home_address_code
     *
     * @return the value of user_info.home_address_code
     *
     * @mbggenerated
     */
    public String getHomeAddressCode() {
        return homeAddressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.home_address_code
     *
     * @param homeAddressCode the value for user_info.home_address_code
     *
     * @mbggenerated
     */
    public void setHomeAddressCode(String homeAddressCode) {
        this.homeAddressCode = homeAddressCode == null ? null : homeAddressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.household_registration_code
     *
     * @return the value of user_info.household_registration_code
     *
     * @mbggenerated
     */
    public String getHouseholdRegistrationCode() {
        return householdRegistrationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.household_registration_code
     *
     * @param householdRegistrationCode the value for user_info.household_registration_code
     *
     * @mbggenerated
     */
    public void setHouseholdRegistrationCode(String householdRegistrationCode) {
        this.householdRegistrationCode = householdRegistrationCode == null ? null : householdRegistrationCode.trim();
    }
}