package cn.beijing.ssfh.entity;

public class Week {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column week.week_id
     *
     * @mbggenerated
     */
    private Integer weekId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column week.week_name
     *
     * @mbggenerated
     */
    private String weekName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week.week_id
     *
     * @return the value of week.week_id
     *
     * @mbggenerated
     */
    public Integer getWeekId() {
        return weekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week.week_id
     *
     * @param weekId the value for week.week_id
     *
     * @mbggenerated
     */
    public void setWeekId(Integer weekId) {
        this.weekId = weekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week.week_name
     *
     * @return the value of week.week_name
     *
     * @mbggenerated
     */
    public String getWeekName() {
        return weekName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week.week_name
     *
     * @param weekName the value for week.week_name
     *
     * @mbggenerated
     */
    public void setWeekName(String weekName) {
        this.weekName = weekName == null ? null : weekName.trim();
    }
}