package cn.beijing.ssfh.entity;

public class WorkReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_report.work_report_id
     *
     * @mbggenerated
     */
    private Integer workReportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_report.tbuser_id
     *
     * @mbggenerated
     */
    private Integer tbuserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_report.work_report_id
     *
     * @return the value of work_report.work_report_id
     *
     * @mbggenerated
     */
    public Integer getWorkReportId() {
        return workReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_report.work_report_id
     *
     * @param workReportId the value for work_report.work_report_id
     *
     * @mbggenerated
     */
    public void setWorkReportId(Integer workReportId) {
        this.workReportId = workReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_report.tbuser_id
     *
     * @return the value of work_report.tbuser_id
     *
     * @mbggenerated
     */
    public Integer getTbuserId() {
        return tbuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_report.tbuser_id
     *
     * @param tbuserId the value for work_report.tbuser_id
     *
     * @mbggenerated
     */
    public void setTbuserId(Integer tbuserId) {
        this.tbuserId = tbuserId;
    }
}