package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.ClassRoom;

public interface ClassRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_room
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer classroomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_room
     *
     * @mbggenerated
     */
    int insert(ClassRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_room
     *
     * @mbggenerated
     */
    int insertSelective(ClassRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_room
     *
     * @mbggenerated
     */
    ClassRoom selectByPrimaryKey(Integer classroomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClassRoom record);
}