package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.CoursePlan;

public interface CoursePlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer coursePlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int insert(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int insertSelective(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    CoursePlan selectByPrimaryKey(Integer coursePlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CoursePlan record);
}