package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.DayTime;

public interface DayTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer dayTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int insert(DayTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int insertSelective(DayTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    DayTime selectByPrimaryKey(Integer dayTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DayTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DayTime record);
}