package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.DepartmentalRole;

public interface DepartmentalRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer departmentalRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_role
     *
     * @mbggenerated
     */
    int insert(DepartmentalRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_role
     *
     * @mbggenerated
     */
    int insertSelective(DepartmentalRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_role
     *
     * @mbggenerated
     */
    DepartmentalRole selectByPrimaryKey(Integer departmentalRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DepartmentalRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DepartmentalRole record);
}