package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.DepartmentalPermissions;

public interface DepartmentalPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_permissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer departmentalPermissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_permissions
     *
     * @mbggenerated
     */
    int insert(DepartmentalPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_permissions
     *
     * @mbggenerated
     */
    int insertSelective(DepartmentalPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_permissions
     *
     * @mbggenerated
     */
    DepartmentalPermissions selectByPrimaryKey(Integer departmentalPermissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DepartmentalPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departmental_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DepartmentalPermissions record);
}