package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.Employment;

public interface EmploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer employmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment
     *
     * @mbggenerated
     */
    int insert(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment
     *
     * @mbggenerated
     */
    int insertSelective(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment
     *
     * @mbggenerated
     */
    Employment selectByPrimaryKey(Integer employmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Employment record);
}