package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.EnterpriseMaintenanceInformationSheet;

public interface EnterpriseMaintenanceInformationSheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_maintenance_information_sheet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer enterpriseMaintenanceInformationSheetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_maintenance_information_sheet
     *
     * @mbggenerated
     */
    int insert(EnterpriseMaintenanceInformationSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_maintenance_information_sheet
     *
     * @mbggenerated
     */
    int insertSelective(EnterpriseMaintenanceInformationSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_maintenance_information_sheet
     *
     * @mbggenerated
     */
    EnterpriseMaintenanceInformationSheet selectByPrimaryKey(Integer enterpriseMaintenanceInformationSheetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_maintenance_information_sheet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnterpriseMaintenanceInformationSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_maintenance_information_sheet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnterpriseMaintenanceInformationSheet record);
}