package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.EnterpriseRecruitmentInformation;

public interface EnterpriseRecruitmentInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_recruitment_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer enterpriseRecruitmentInformationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_recruitment_information
     *
     * @mbggenerated
     */
    int insert(EnterpriseRecruitmentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_recruitment_information
     *
     * @mbggenerated
     */
    int insertSelective(EnterpriseRecruitmentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_recruitment_information
     *
     * @mbggenerated
     */
    EnterpriseRecruitmentInformation selectByPrimaryKey(Integer enterpriseRecruitmentInformationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_recruitment_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnterpriseRecruitmentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_recruitment_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnterpriseRecruitmentInformation record);
}