package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.EnterpriseTeacher;

public interface EnterpriseTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_teacher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer enterpriseTeacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_teacher
     *
     * @mbggenerated
     */
    int insert(EnterpriseTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_teacher
     *
     * @mbggenerated
     */
    int insertSelective(EnterpriseTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_teacher
     *
     * @mbggenerated
     */
    EnterpriseTeacher selectByPrimaryKey(Integer enterpriseTeacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnterpriseTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnterpriseTeacher record);
}