package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.EnterpriseContact;

public interface EnterpriseContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_contact
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer enterpriseContactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_contact
     *
     * @mbggenerated
     */
    int insert(EnterpriseContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_contact
     *
     * @mbggenerated
     */
    int insertSelective(EnterpriseContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_contact
     *
     * @mbggenerated
     */
    EnterpriseContact selectByPrimaryKey(Integer enterpriseContactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_contact
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnterpriseContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_contact
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnterpriseContact record);
}