package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.GradeStudent;

public interface GradeStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gradeStudentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_student
     *
     * @mbggenerated
     */
    int insert(GradeStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_student
     *
     * @mbggenerated
     */
    int insertSelective(GradeStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_student
     *
     * @mbggenerated
     */
    GradeStudent selectByPrimaryKey(Integer gradeStudentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GradeStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GradeStudent record);
}