package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.GradeSircle;

public interface GradeSircleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_sircle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gradeSircleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_sircle
     *
     * @mbggenerated
     */
    int insert(GradeSircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_sircle
     *
     * @mbggenerated
     */
    int insertSelective(GradeSircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_sircle
     *
     * @mbggenerated
     */
    GradeSircle selectByPrimaryKey(Integer gradeSircleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_sircle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GradeSircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_sircle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GradeSircle record);
}