package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.MenuPermissions;

public interface MenuPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_permissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer menuPermissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_permissions
     *
     * @mbggenerated
     */
    int insert(MenuPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_permissions
     *
     * @mbggenerated
     */
    int insertSelective(MenuPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_permissions
     *
     * @mbggenerated
     */
    MenuPermissions selectByPrimaryKey(Integer menuPermissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MenuPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MenuPermissions record);
}