package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.Production;

public interface ProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int insert(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int insertSelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    Production selectByPrimaryKey(Integer productionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Production record);
}