package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.SircleTimePart;

public interface SircleTimePartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sircle_time_part
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sircleTimePartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sircle_time_part
     *
     * @mbggenerated
     */
    int insert(SircleTimePart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sircle_time_part
     *
     * @mbggenerated
     */
    int insertSelective(SircleTimePart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sircle_time_part
     *
     * @mbggenerated
     */
    SircleTimePart selectByPrimaryKey(Integer sircleTimePartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sircle_time_part
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SircleTimePart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sircle_time_part
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SircleTimePart record);
}