package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.State;

public interface StateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer stateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int insert(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int insertSelective(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    State selectByPrimaryKey(Integer stateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(State record);
}