package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.StudentInformation;

public interface StudentInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_information
     *
     * @mbggenerated
     */
    int insert(StudentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_information
     *
     * @mbggenerated
     */
    int insertSelective(StudentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_information
     *
     * @mbggenerated
     */
    StudentInformation selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentInformation record);
}