package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.StudyParts;

public interface StudyPartsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_parts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer studyPartsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_parts
     *
     * @mbggenerated
     */
    int insert(StudyParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_parts
     *
     * @mbggenerated
     */
    int insertSelective(StudyParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_parts
     *
     * @mbggenerated
     */
    StudyParts selectByPrimaryKey(Integer studyPartsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_parts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudyParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_parts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudyParts record);
}