package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.Tbuser;

public interface TbuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tbuserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    int insert(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    int insertSelective(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    Tbuser selectByPrimaryKey(Integer tbuserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbuser record);
}