package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.TeachingPlan;

public interface TeachingPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaching_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer techingPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaching_plan
     *
     * @mbggenerated
     */
    int insert(TeachingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaching_plan
     *
     * @mbggenerated
     */
    int insertSelective(TeachingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaching_plan
     *
     * @mbggenerated
     */
    TeachingPlan selectByPrimaryKey(Integer techingPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaching_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeachingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaching_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeachingPlan record);
}