package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.TeacherCourse;

public interface TeacherCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer teacherCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated
     */
    int insert(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated
     */
    int insertSelective(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated
     */
    TeacherCourse selectByPrimaryKey(Integer teacherCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_course
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeacherCourse record);
}