package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.TestScore;

public interface TestScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer testCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score
     *
     * @mbggenerated
     */
    int insert(TestScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score
     *
     * @mbggenerated
     */
    int insertSelective(TestScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score
     *
     * @mbggenerated
     */
    TestScore selectByPrimaryKey(Integer testCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestScore record);
}