package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.UploadPath;

public interface UploadPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_path
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pathId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_path
     *
     * @mbggenerated
     */
    int insert(UploadPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_path
     *
     * @mbggenerated
     */
    int insertSelective(UploadPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_path
     *
     * @mbggenerated
     */
    UploadPath selectByPrimaryKey(Integer pathId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_path
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UploadPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_path
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UploadPath record);
}