package cn.beijing.ssfh.mapper;

import cn.beijing.ssfh.entity.WorkReport;

public interface WorkReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer workReportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_report
     *
     * @mbggenerated
     */
    int insert(WorkReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_report
     *
     * @mbggenerated
     */
    int insertSelective(WorkReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_report
     *
     * @mbggenerated
     */
    WorkReport selectByPrimaryKey(Integer workReportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkReport record);
}